Service:
  name: {{ cookiecutter.root_directory_name }}
  version:
  port: 8080
{% if cookiecutter.use_database == 'y' %}  
Database:
  user:
  password:
  host:
  port:
  name:
{% endif %}
{% if cookiecutter.use_cache == 'y' %}
Cache:
  address:
  password:
  db:
{% endif %}
{% if cookiecutter.use_kafka == 'y' %}
Kafka:
  enabled:
  version:
  consume_only:
  consumer_group_id:
  schema_registration:
  brokers:
  TLS:
    ca_cert_pem:
    cert_pem:
    key_pem:
    skip_verify:
    timeout_secs:
{% endif %}