####### LINTER DOCS #######
#https://golangci-lint.run/
###########################


run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 1m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false

output:
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: false
  # Format: colored-line-number|line-number|json|colored-tab|tab|checkstyle|code-climate|junit-xml|github-actions|teamcity
  #
  # Multiple can be specified by separating them by comma, output can be provided
  # for each of them by separating format name and path by colon symbol.
  # Output path can be either `stdout`, `stderr` or path to the file to write to.
  # Example: "checkstyle:report.xml,json:stdout,colored-line-number"
  #
  # Default: colored-line-number
  format: json:issues.json
  # Sort results by: filepath, line and column.
  # Default: false
  sort-results: true
  # Which files to skip: they will be analyzed, but issues from them won't be reported.
  # There is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not, please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  skip-files:
    - internal/accounts/service/parser.go

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - goconst
    - gocyclo
    - goerr113
    - gofmt
    - gomnd
    - misspell
    - nestif
    - stylecheck
    - sqlclosecheck
    - unparam

# For all linter setting check https://golangci-lint.run/usage/linters
linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 70
    # Should ignore tests.
    # Default: false
    skip-tests: true

  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 70

  dupl:
    # Tokens count to trigger issue.
    # Default: 150
    threshold: 300

  goconst:
    # Search also for duplicated numbers.
    # Default: false
    numbers: true
    # Minimum value, only works with goconst.numbers
    # Default: 3
    min: 2
    # Maximum value, only works with goconst.numbers
    # Default: 3
    max: 2

  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 4

issues:
  exclude:
    - "does not match go tool version"
    - "undefined: opentracing"
    - "undefined: redis"
    - "undefined: echo"
    - "undefined: yaml"
    - "undefined: apilogger"
    - "undefined: kafka"