basePath: /v1
consumes:
- application/json
definitions:
  Thing:
    description: Thing is db record of thing
    properties:
      category_id:
        format: uint64
        type: integer
        x-go-name: CategoryID
      id:
        format: uint64
        type: integer
        x-go-name: ID
      image:
        type: string
        x-go-name: Image
    type: object
    x-go-package: {{ cookiecutter.module_name }}/internal/{{ cookiecutter.main_domain }}/entity
  badRequestRS:
    description: Bad request
    properties:
      error:
        description: |-
          Error message
          in: body
        type: string
        x-go-name: Body
    type: object
    x-go-name: badRequestResp
    x-go-package: {{ cookiecutter.module_name }}/internal/api/v1/dto
  genericErrorRS:
    description: Generic error
    properties:
      error:
        description: |-
          Error message
          in: body
        type: string
        x-go-name: Body
    type: object
    x-go-name: genericErrorResp
    x-go-package: {{ cookiecutter.module_name }}/internal/api/v1/dto
  genericSuccessRS:
    description: Generic success
    properties:
      Data:
        description: 'in: body'
        type: object
    type: object
    x-go-name: genericSuccessResp
    x-go-package: {{ cookiecutter.module_name }}/internal/api/v1/dto
  getThingRS:
    properties:
      thing:
        $ref: '#/definitions/Thing'
    type: object
    x-go-package: {{ cookiecutter.module_name }}/internal/api/v1/dto
  serverErrorRS:
    description: Internal server error
    properties:
      body:
        description: |-
          Error message
          in: body
        type: string
        x-go-name: Body
    type: object
    x-go-name: serverErrorResp
    x-go-package: {{ cookiecutter.module_name }}/internal/api/v1/dto
host: localhost:8080
info:
  description: {{ cookiecutter.app_name }} service
  title: {{ cookiecutter.app_name }} service
  version: "1.0"
paths:
  /thing:
    get:
      description: Retrieves a thing
      operationId: getThingRQ
      parameters:
      - in: query
        name: id
        type: string
        x-go-name: ID
      responses:
        "200":
          description: getThingRS
          schema:
            $ref: '#/definitions/getThingRS'
        "400":
          description: badRequestRS
          schema:
            $ref: '#/definitions/badRequestRS'
        "500":
          description: serverErrorRS
          schema:
            $ref: '#/definitions/serverErrorRS'
      summary: Retrieves a thing
      tags:
      - things
produces:
- application/json
schemes:
- http
security:
- api_key: []
securityDefinitions:
  api_key:
    in: header
    name: api-key
    type: apiKey
swagger: "2.0"
